### ISSUE TITLE
Texture issue with slim fire

### ISSUE THREAD

**Issue by RearMisser** [Crystal-Nest/slim-fire#1]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [X] I have installed the mod properly

### Current behavior

When I use the slim fired texture pack with the soul fired mod, every mob that catches on soul fire has a null texture on it along with the fire.

### Expected behavior

When mob catches on soul fire there a null texture.

### Steps to reproduce

Enter world
Set mobs on soul fire.

### Minecraft version

1.19.2

### Mod loader version

Forge 43.3.0

### Mod version

Soul Fired 4.0.3 Slim Fire 1.0

### Other mods

none

![2024-09-11_21 18 38](https://github.com/user-attachments/assets/6efae6c1-ea3d-4b6e-b28c-9c040322128f)

**Comment by Crystal-Spider** [comment]
This bug, present in 1.19.2 and lower only, has been fixed with v1.0.1.
